### ISSUE TITLE
Error with gcc in linux

### ISSUE THREAD

**Issue by majidkamali1370** [trolleyyy/xlinq#1] opened 2016-11-07 06:00 UTC
Hi
I added xlinq headers to my project and also added support for c++14 to my project, but while compiling, I get following error on line 96 of xlinq_average.h:

`error: there are no arguments to 'average' that depend on a template parameter, so a declaration of 'average' must be available [-fpermissive]
    return enumerable ^ select(_valueConverter) ^ average();
                                                          ^
../test_Utils/xlinq/xlinq_average.h:96:58: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)`

When I comment #include "xlinq_average.h" from xlinq.h and use headers, I get another error:

`int arr[] = { 1, 2, 3, 4, 5, 6, 7, 8, 9 };
auto test = from(arr);`

Error:
`error: no matching function for call to 'begin(int [9])'
using TRefElem = decltype(*std::begin(std::declval<TContainer>()));`
at line 54 of xlinq_std.h

**Comment by trolleyyy** [comment] 2016-11-07 21:03
Hi,

first of all thanks for trying to run it on GCC. This library is still in development and I even didn't tried to compile it on other compilers than Visual C++. I will sure do it, but first of all I want to create some basic form of this library and resolve issues with performance and portability (like that one) later.

**Comment by majidkamali1370** [comment] 2016-11-08 07:46
Can't you downgrade library to use c++11  :-D

**Comment by trolleyyy** [comment] 2016-11-08 17:05
I guess, that problem with "no matching begin" may be caused by not including `<iterator>` header. It contains definition of `std::begin`, and I guess that Visual C++ may not need to include it explicitly. You may want to try to add `#include <iterator>` to xlinq_std.h file and see if it helps.

Maybe I can target c++11, it was my initial idea. Still I want to create basic form of library first, support all common LINQ operators, and then look at portability, compatilibity and performance issues.

**Comment by majidkamali1370** [comment] 2016-11-09 07:26
I commented `#include "xlinq_average.h"` line in xlinq.h file for now.
Adding iterator header file did not change anything.

with below test:
`int arr[] = { 1, 2, 3, 4, 5, 6, 7, 8, 9 };
IEnumerable<int>::Ptr test = from(arr);`
I get following error:
`error: conversion from 'void' to non-scalar type 'xlinq::IEnumerable<int>::Ptr {aka std::shared_ptr<xlinq::IEnumerable<int> >}' requested
     IEnumerable<int>::Ptr test = from(arr);
                                  ~~~~^~~~~`
and above that: (in xlinq_std.h)
`error: invalid initialization of non-const reference of type 'int (&)[9]' from an rvalue of type 'int [9]'
   using TRefElem = decltype(*std::begin(std::declval<TContainer>()));
                              ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~`
and lots of similar errors as below: (in range_access.h)
`error: request for member 'begin' in '__cont', which is of non-class type 'const int [9]'
     begin(const _Container& __cont) -> decltype(__cont.begin())
                                                 ~~~~~~~^~~~~`
and then the above `no matching ...` error

**Comment by trolleyyy** [comment] 2017-04-15 15:28
Hey, if you are still interested in this project - i started to rewrite it with new syntax inspired by cpplinq project. It now supports g++ and c++11.

**Comment by trolleyyy** [comment] 2017-06-09 19:59
I'm closing this issue because it is not relevant anymore.

**Closed as completed by trolleyyy** 2017-06-09 19:59 UTC
